name: Steep

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - "3.3"
        rails-version:
          - "8.0"
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails-version }}.gemfile

    name: Steep - Ruby ${{ matrix.ruby-version }} on Rails ${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }} on Rails ${{ matrix.rails-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Verify Ruby Types (Static)
        run: |
          bundle exec rake steep
      - name: Verify Ruby Types (Runtime)
        run: |
          bundle exec rake rbs:spec
